# Generated by Django 3.1 on 2020-08-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('réservée', 'réservée'), ('terminé', 'terminé'), ('rejeté', 'rejeté')], default='réservée', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('فحص طبي', 'فحص طبي'), ('تصوير بالاشعة', 'تصوير بالاشعة'), ('اكمال علاج سابق', 'اكمال علاج سابق'), ('استخراج وثائق طبية', 'استخراج وثائق طبية')], max_length=200),
        ),
    ]
