# Generated by Django 3.1 on 2020-08-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200812_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='notes',
        ),
    ]
