# Generated by Django 3.1 on 2020-08-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_status_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
